[workspace]
resolver = "3"
members = [
    "Engine/Shaders",

    "Engine/Crates/bin/editor",

    "Engine/Crates/RuntimeCore/*",
    "Engine/Crates/RuntimeCore/RHI/",
    "Engine/Crates/RuntimeCore/RHI/rhi_core/",
    "Engine/Crates/RuntimeCore/RHI/rhi_core/rhi_vulkan",
    "Engine/Crates/RuntimeCore/RHI/rhi_core/rhi_dx12",
    "Engine/Crates/RuntimeCore/RHI/rhi_core/rhi_metal"
]
exclude = [
    "Engine/Shaders"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Lance Wallis <walance@pvas.me>"]
license = ""
repository = ""
